import subprocess
import threading
import sys
import time
import re

sync_log = open("multiverse_sync.log", "w")
sync_lock = threading.Lock()

def monitor_output(process, p_id):
    """Reads stdout from a child process and filters key events/errors."""
    with open(f"p{p_id}_full.log", "a") as full_log:
        for line in iter(process.stdout.readline, ''):
            if not line: break
            full_log.write(line)
            full_log.flush()

            # Expanded filter to stop suppressing setup info, routing, and Lua errors
            important_tags = [
                "[HEARTBEAT]", "FATAL", "Divergence",
                "[SYSTEM]", "[STUN]", "[LOBBY]", "[ICE]", "[SYNC]",
                "[ROUTING]", "[MATCHMAKER]", "[DIAGNOSTIC]", # <-- ADDED THESE
                "error", "Exception", "luajit:"
            ]

            if any(tag in line for tag in important_tags):
                with sync_lock:
                    formatted_line = f"[P{p_id}] {line}"
                    sys.stdout.write(formatted_line)
                    sync_log.write(formatted_line)
                    sync_log.flush()

def main():
    print("========================================")
    print(" IGNITING SPLIT-BRAIN WAN MULTIVERSE ")
    print("========================================")

    # Determine Harness Mode
    print("Select Harness Mode:")
    print(" (H)ost Machine - Boots Node 0 (Host) and Nodes 1-3")
    print(" (J)oin Machine - Boots Nodes 4-7 into an existing Lobby")
    sys.stdout.write("> ")
    sys.stdout.flush()
    mode = sys.stdin.readline().strip().upper()

    nodes = []

    if mode.startswith('H'):
        # ==========================================
        # HOST MACHINE PROTOCOL (Nodes 0 - 3)
        # ==========================================
        print("\n[HARNESS] Booting Node 0 (Host) on Port 50000...")
        host_proc = subprocess.Popen(
            ['luajit', 'main.lua'],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1
        )

        host_proc.stdin.write("0\n")
        host_proc.stdin.write("H\n")
        host_proc.stdin.flush()

        nodes.append(host_proc)
        lobby_id = None
        
        print("[HARNESS] Waiting for Node 0 to negotiate STUN and secure a Lobby ID...")

        with open("p0_full.log", "w") as f0:
            while True:
                line = host_proc.stdout.readline()
                if not line:
                    print("[HARNESS] FATAL: Host crashed before creating lobby!")
                    sys.exit(1)
                
                f0.write(line)
                f0.flush()
                sys.stdout.write(f"[P0] {line}")
                
                match = re.search(r"holding room:\s*([A-Z0-9]{4})", line)
                if match:
                    lobby_id = match.group(1)
                    print("\n=======================================================")
                    print(f"✅ LOBBY CREATED. GIVE THIS ID TO MACHINE 2: {lobby_id}")
                    print("=======================================================\n")
                    break

        threading.Thread(target=monitor_output, args=(host_proc, 0), daemon=True).start()

        print("[HARNESS] Booting local clients (Nodes 1, 2, 3)...")
        for i in range(1, 4):
            time.sleep(0.2)
            proc = subprocess.Popen(
                ['luajit', 'main.lua'],
                stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1
            )
            proc.stdin.write(f"{i}\n")
            proc.stdin.write("J\n")
            proc.stdin.write(f"{lobby_id}\n")
            proc.stdin.flush()
            nodes.append(proc)
            threading.Thread(target=monitor_output, args=(proc, i), daemon=True).start()

        print("\n[HARNESS] Machine 1 Ready. Waiting for Machine 2 to join...\n")

    elif mode.startswith('J'):
        # ==========================================
        # JOIN MACHINE PROTOCOL (Nodes 4 - 7)
        # ==========================================
        print("\nEnter the 4-Character Lobby ID generated by Machine 1:")
        sys.stdout.write("> ")
        sys.stdout.flush()
        lobby_id = sys.stdin.readline().strip().upper()

        print(f"\n[HARNESS] Booting remote clients (Nodes 4, 5, 6, 7) into Lobby {lobby_id}...")
        for i in range(4, 8):
            time.sleep(0.2)
            proc = subprocess.Popen(
                ['luajit', 'main.lua'],
                stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1
            )
            proc.stdin.write(f"{i}\n")
            proc.stdin.write("J\n")
            proc.stdin.write(f"{lobby_id}\n")
            proc.stdin.flush()
            nodes.append(proc)
            threading.Thread(target=monitor_output, args=(proc, i), daemon=True).start()

        print("\n[HARNESS] Machine 2 Ready. Awaiting lockstep quorum...\n")
    
    else:
        print("[HARNESS] Invalid mode selected. Exiting.")
        sys.exit(1)

    # ==========================================
    # WAIT STATE
    # ==========================================
    try:
        for node in nodes:
            node.wait()
    except KeyboardInterrupt:
        print("\n[HARNESS] Ctrl+C Detected. Terminating Multiverse.")
        for node in nodes:
            node.terminate()
        sync_log.close()
        print("[HARNESS] Clean Exit.")

if __name__ == "__main__":
    main()
